set nocompatible              " be iMproved, required
filetype off                  " required
syntax on
filetype plugin indent on
set number
set wildignore+=*\\target\\*,*\\.svn\\*,*\\.git\\*,*\\workspace\\*
set ruler
set visualbell
set encoding=utf-8
set ts=2 sts=2 sw=2 expandtab
set laststatus=2
imap jj <Esc>
nnoremap <Tab> >>_
nnoremap <S-Tab> <<_
inoremap <S-Tab> <C-D>
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv

python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

