# If you come from bash you might have to change your $PATH.
echo 'Applying zshrc'
source ~/dotfiles/zsh/antigen.zsh

antigen use oh-my-zsh

antigen bundle bower
antigen bundle docker
antigen bundle docker-compose
antigen bundle git
antigen bundle gradle
antigen bundle kubectl
antigen bundle minikube
antigen bundle node
antigen bundle npm
antigen bundle osx
antigen bundle timer
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme jan-auer/zsh-multiline
antigen apply

bindkey -v

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm

[[ -s ~/.profile ]] && source ~/.profile

